# the name of this file must be exactly like the name of the application
eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # shows that we have to fetch information about registered microservices from Discovery service
          enabled: true
      routes:
        # if the request path is /api/v1/students/**, it is redirected to localhost:8090 (aka students)
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/v1/students/**
        # if the request path is /api/v1/schools/**, it is redirected to localhost:8070 (aka schools)
        - id: schools
          uri: lb://schools
          predicates:
            - Path=/api/v1/schools/**
management:
  tracing:
    sampling:
      probability: 1.0